### ISSUE TITLE
importing 13Fs filing

### ISSUE THREAD

**Issue by yogeshdesh17** [toddwschneider/sec-13f-filings#5]
I am getting below error while importing data.
bundle exec rake filings:seed_minimal_db
2023-01-07 09:30:42 UTC: beginning minimal db seed, might take a few minutes…
2023-01-07 09:30:42 UTC: importing 13Fs filed in 2023 Q1
2023-01-07 09:30:43 UTC: importing 13Fs filed in 2022 Q4
2023-01-07 09:30:46 UTC: importing 13Fs filed in 2022 Q3
2023-01-07 09:30:49 UTC: importing 13Fs filed in 2022 Q2
2023-01-07 09:30:52 UTC: queueing jobs for sample managers
2023-01-07 09:30:52 UTC: processing filings data
2023-01-07 09:30:52 UTC: deleting unprocessed filings
2023-01-07 09:30:52 UTC: done, minimal db now available

**Comment by yogeshdesh17** [comment]
I believe its because of this error.
(base) yogeshdesh17@Yogeshs-MacBook-Air sec-13f-filings-main % yarn                
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[4/4] 🔨  Building fresh packages...
[1/3] ⢀ fsevents
[-/3] ⢀ waiting...
error /Users/yogeshdesh17/sec-13f-filings-main/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/yogeshdesh17/sec-13f-filings-main/node_modules/node-sass
Output:
Building: /opt/homebrew/Cellar/node/19.4.0/bin/node /Users/yogeshdesh17/sec-13f-filings-main/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/opt/homebrew/Cellar/node/19.4.0/bin/node',
gyp verb cli   '/Users/yogeshdesh17/sec-13f-filings-main/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@19.4.0 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/yogeshdesh17/sec-13f-filings-main/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/yogeshdesh17/sec-13f-filings-main/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/yogeshdesh17/sec-13f-filings-main/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/yogeshdesh17/sec-13f-filings-main/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/yogeshdesh17/sec-13f-filings-main/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/yogeshdesh17/sec-13f-filings-main/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:190:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/yogeshdesh17/sec-13f-filings-main/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/yogeshdesh17/sec-13f-filings-main/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/yogeshdesh17/sec-13f-filings-main/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/yogeshdesh17/sec-13f-filings-main/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/yogeshdesh17/sec-13f-filings-main/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/yogeshdesh17/sec-13f-filings-main/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:190:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /opt/anaconda3/bin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /opt/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:419:12)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:456:11)
gyp ERR! stack     at Socket.emit (node:events:513:28)
gyp ERR! stack     at Pipe.<anonymous> (node:net:317:12)
gyp ERR! System Darwin 22.1.0
gyp ERR! command "/opt/homebrew/Cellar/node/19.4.0/bin/node" "/Users/yogeshdesh17/sec-13f-filings-main/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/yogeshdesh17/sec-13f-filings-main/node_modules/node-sass
gyp ERR! node -v v19.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by toddwschneider** [comment]
Hi @yogeshdesh17, unfortunately I'm not sure I can help debug the yarn setup on your local machine. Sorry not to be of more help, but I'll leave this open in case others have ideas
